--INSERT INTO public.tipo_pessoa (id,ativo,descricao) VALUES (1,true,'Usuário');
--INSERT INTO public.tipo_pessoa (id,ativo,descricao) VALUES (2,true,'Vereador');
--INSERT INTO public.tipo_pessoa (id,ativo,descricao) VALUES (3,true,'Servidor');
--INSERT INTO public.tipo_pessoa (id,ativo,descricao) VALUES (4,true,'Assessor');